[package]
name = "pos_core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pbkdf2 = "0.12"
sha2 = "0.10"
hex = "0.4"
subtle = "2"
rand = "0.8"
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
